### ISSUE TITLE
RE2::Regexp.match return is different than Regexp.match

### ISSUE THREAD

**Issue by sk-** [mudge/re2#26]
In plain ruby we have:
```ruby
Regexp.new('a').match("a")
 => #<MatchData "a">
Regexp.new('a').match("b")
 => nil
```

whereas in `re2`:

```ruby
RE2::Regexp.new('a').match("a")
 => true
RE2::Regexp.new('a').match("b")
 => false
```

**Comment by mudge** [comment]
In retrospect, I think the multiple return types of `RE2::Regexp#match` are a mistake: it should just consistently return `RE2::MatchData` objects (even if they contain no captured groups) or `nil`.

Unfortunately, this would be a breaking API change but we could use a major new version to rethink the API. I'm not sure whether we should be more like Ruby's API or try to match the underlying [re2 C++ interface](https://github.com/google/re2/blob/master/re2/re2.h).
